### PR TITLE
[PYPI] Turn into front-end API/package #21

### PR DESCRIPTION
**Pull request by juanpisss**
Will be used for the planned generator as a showcase of sv-dlp's capabilities
  - The generator will be built on top of Flask, but will use sv-dlp as a backend
  - It will be a separate program that can be downloaded from sv-dlp
  
TODO:

- [x] #10
- [x] Write initialization constructor
  - [x] Implement download_panorama & postdownload inner class
  - [x] Implement metadata features
    - [x] Implement Historical Panoramas
    - [x] Obtain linked panoramas
  - [x] #13 
      - Call service scripts automatically (instead of manually)
  - [x] Adjust Apple script to constructor's standards
- [x] Configure distutils/setup.py
- [x] Write documentation
    - [x] Module Basics & Getting Started
    - [x] Command Line Interface - User Guide
    - [x] Class Documentation
    - [x] Downloading Process
    - [x] Services - Getting Started

### CODE REVIEW

**Comment by juanpisuribe13** [comment]
Essential tasks finished. Will test the module by tomorrow and fix some stuff if required.

#13 isn't really *that* automatic since it just obtains the available services, so the automatization has to depend on the developer instead.

**Comment by juanpisuribe13** [comment]
I MIGHT plan on doing a sv-dlp viewer program (as an example of what sv-dlp is capable of doing internally), so i might need to add tile_urls & north/south faces in metadata - idk how to explain

**Comment by juanpisuribe13** [comment]
Testing done! Will adapt CLI to it, then configure setup.py, and finally write the documentation

**Comment by juanpisss** [comment]
CLI Rewrite & SetupTools Finished.
Will begin writing the documentation. After that, polish some stuff so I can merge the branches and ship it

**Comment by juanpisss** [comment]
I might write the package documentation on <readthedocs.io> instead, as it seems easier and convenient for me since most of the process is automatic.
CLI documentation will stay on GitHub Wikis though,

**Comment by juanpisss** [comment]
Almost finished writing the documentation! Services Page is all that is left.

I found out that `sv_dlp.download_panorama()` doesn't work when only a Panorama ID is parsed for a service that requires MD but only works for LAT/LNG (remember that it needs the metadata for it to work).
Tomorrow I'm gonna try to write a workaround for that.

Also first iteration of `raw_md.pano` in `sv_dlp.services.apple` isn't the closest to the coordinate, so I'm gonna make it scan all iterations and see which one is the closest.

**Comment by juanpisss** [comment]
I'm back after dealing with finals & mental health.
Will do documentation on contributing services, then push it to main branch & publish it on PyPi. Release might be a bit wonky, but will get better as time goes on.

**Comment by juanpisss** [comment]
Done! Gonna do a bit of tinkering with GitHub WorkFlows and I'm finally done

**Pull request merged**
